### ISSUE TITLE
Error upon clicking "Create Army"

### ISSUE THREAD

**Issue by cronsOP125** [pwestling/battlescribe-roster-parser#2] opened 2019-07-10 20:12 UTC
![image](https://user-images.githubusercontent.com/29277264/61001279-2e1f7e00-a314-11e9-87a0-d6aab1e3fd06.png)
This error occurred shortly after clicking Create Army. After doing so, the button is now greyed out. There were 2 unselected buttons, since they were extras created by the Battlescribe formatting for the Talos Pain Engine.

**Comment by pwestling** [comment] 2019-07-11 05:29
Does this happen consistently, and if so can you upload the roster file that's having the issue?

**Comment by pwestling** [comment] 2019-07-11 06:44
I've updated with better logging for these cases, and some code that should always unlock the button so you can try again. If you're still able to reproduce the error with the new version let me know, and please send me the roster file and roster code that's giving you the error.

**Comment by BaconCatBug** [comment] 2019-07-12 01:36
I get this same error (though it now just says "got error") with the following roster. 
[2k - Medium Nids.zip](https://github.com/pwestling/battlescribe-roster-parser/files/3384588/2k.-.Medium.Nids.zip)

**Comment by pwestling** [comment] 2019-07-12 17:20
It looks like in your case the Acid Maw genestealers are tripping it up. I will see if I can get this fixed.

**Comment by pwestling** [comment] 2019-07-12 21:12
Ok these issues should be fixed now. Let me know if you see problems like this again.

**Closed as completed by pwestling** 2019-07-12 21:12 UTC
