### ISSUE TITLE
Stalker bolt rifle

### ISSUE THREAD

**Issue by GOTOTHEUNKNOWN** [pwestling/battlescribe-roster-parser#23] opened 2020-04-05 03:24 UTC
stalker bolt rifle is not recognized by the tool and as such assumes that my space marne intersessors are recognized to have a bolt rife and not a stalker rifle

**Comment by pwestling** [comment] 2020-04-14 05:11
Hard to tell, but I think this is a duplicate of https://github.com/pwestling/battlescribe-roster-parser/issues/19. If you don't think so, please open a new ticket with a roster demonstrating the issue.

**Closed as completed by pwestling** 2020-04-14 05:11 UTC
Labels: bug
